# Generated by Django 4.0.6 on 2024-03-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(blank=True, to='join_backend.subtask'),
        ),
    ]
