# Generated by Django 4.0.6 on 2024-03-31 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend', '0003_remove_subtask_description_remove_task_subtasks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nasme',
        ),
    ]
