# Generated by Django 4.0.6 on 2024-03-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend', '0004_rename_name_category_nasme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nasme',
            new_name='name',
        ),
    ]
